### ISSUE TITLE
Funktion getStone(Integer stoneId) in Klasse DatabaseService.java erstellen

### ISSUE THREAD

**Issue by bennySwiers** [ginetrix/SDL#3]
In der Klasse DatabaseService.java muss es eine Funktion geben, die einen Stein an Hand einer Stein-Id aus der Datenbank holt. Der Recommender wird nur die Ids der Steine liefern. Der DatabaseService muss dann das entsprechende Stone-Objekt liefern können.

**Comment by bennySwiers** [comment]
In der Klasse DatabaseService.java muss es eine Funktion geben, die einen Stein an Hand einer Stein-Id aus der Datenbank holt. Der Recommender wird nur die Ids der Steine liefern. Der DatabaseService muss dann das entsprechende Stone-Objekt liefern können.

**Comment by oliver132** [comment]
ez done
