### ISSUE TITLE
Wechselnde Farbe bei http://localhost:8080/SDL/

### ISSUE THREAD

**Issue by bennySwiers** [ginetrix/SDL#7]
Die wechselnde Farbe wäre vor 20 Jahren toll gewesen, aber nicht mehr jetzt.

**Comment by Pandu53** [comment]
Die Seite verwenden wir einfach nicht mehr und nehmen als Startseite einfach dierekt die Login.jsp.
Falls man sich registrieren muss kann man über die Nav-Bar zur Registration wechseln.
