### ISSUE TITLE
Programmführung schaffen

### ISSUE THREAD

**Issue by bennySwiers** [ginetrix/SDL#8]
Momentan muss der Nutzer über die Urls navigieren. Das können wir keinem anbieten. Es muss eine Programmführung geschaffen werden, über die der Nuzter durch klicken, oder Weiterleitungen von A nach B nach C kommt (z.B. über eine Navbar).

**Comment by Pandu53** [comment]
Navbar ist gemacht, muss nur noch ein "Logout" hinzugefügt werden.
